### ISSUE TITLE
Support secure web socket?

### ISSUE THREAD

**Issue by T-Pham** [SuitestAutomation/BrightWebSocket#9]
Hi,

Can someone shed me some light on how far we are from supporting secure web socket?

I found this commit which seems related: https://github.com/SuitestAutomation/BrightWebSocket/commit/1cb833dc89f42f60a658fe6680e6ebcf213a0c3e
The commit message says:
> Started work on TLS
> It is not functional at the moment. The client needs to parse the server
certificate and send the client key exchange

Do parsing server certificate and sending client key exchange the only missing parts to make secure web socket work? Can you give me an idea how hard those would be and maybe point me to some resources (eg documents) to start the work if it is at all possible?

**Comment by polomsky** [comment]
Hello. As far as I know Roku API does not provide TLS connection without HTTP request. And implementation of TLS stack by hand is nearly impossible. First what you need is cryptographically secure random number generator. The parsing of a certificate is very small part of whole work.

For TLS stack you need (let's say TLS 1.3):
- cryptographically secure random generator
- implementation of elliptic curves, maybe also RSA (depends on certificate)
- implementation of Chacha20Poly1305 (because AES would be slower without HW acceleration)

I don't dare to guess how slow could be this implementation but imho some kind of long polling is much more realistic.

**Comment by T-Pham** [comment]
Thank you for your insight.
It sounds adding support for secure web socket would require deep knowledge of cryptography as well as lots of effort, if that is at all possible.
